version: "3.9"
services:
  api:
    build: .
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: cookie
      POSTGRES_PASSWORD: clicker
      POSTGRES_DB: cookieclicker
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
